
title: Streamers Peruanos.dev
email: your-email@example.com
description: Streamers that shows video code
baseurl: "" 
url: "" 

theme: minima 

collections:
  speakers:
    output: true
    permalink: /streamers/:name

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/  
